deployment:
  svc: true
  bff: true
  ui: true

product:
  info:
    data:
      description: "OneCX Bookmark"
      imageUrl: ""
      iconName: "bookmark"
      displayName: "OneCX Bookmark"
      basePath: "/bookmark"
